### ISSUE TITLE
Naming needs improvement

### ISSUE THREAD

**Issue by DonSchenck** [DonSchenck/PoshStack#247]
New-ComputeServer should be New-OpenStackComputeServer, for example.

But my question is: How to separate cmdlets that return one and only one object versus a cmdlet that returns a collection of objects? Get-ComputeServer vs. Get-ComputeServers ??

**Comment by rchaganti** [comment]
Yes, the New-OpenStackComputeServer makes better sense. 

Regarding plurals, you don't have to implement two cmdlets. For example, Get-OpenStackComputeServer can be written to return all objects when no parameters are provided. The additional filtering can be done using a parameter like -Name or -Id that refers to one or more compute servers. 

```
#Get all compute server objects
Get-OpenStackComputeServer

#Get a specific compute server
Get-OpenStackComputeServer -Name Contoso

#Get one or more compute servers
Get-OpenStackComputeServer -Name Contoso, Rackspace
```

**Comment by DonSchenck** [comment]
I hindsight, I see that you're correct.

I'm anxious to make the changes; it's not a lot of effort and it is The Right Thing to do.

I'll label the current state of PoshStack as a "alpha" and make the changes and move forward.

Sound good?

**Comment by rchaganti** [comment]
Yes sir. Thanks for hearing out the feedback. I started looking at the code and may have some more feedback by tomorrow.
