### ISSUE TITLE
Listing Commands

### ISSUE THREAD

**Issue by gomker** [DonSchenck/PoshStack#293]
When I run  "Get-Command -Module PoshStack"
I only see the following commands available

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-OpenStackAccount                               0.0.1      PoshStack
Function        Get-OpenStackIdentityProviderOpenStack             0.0.1      PoshStack
Function        Invoke-Exception                                   0.0.1      PoshStack
Function        New-RandomComplexPassword                          0.0.1      PoshStack
Function        Show-OpenStackAccounts                             0.0.1      PoshStack
Function        Show-UntestedWarning                               0.0.1      PoshStack
```
In other modules I work on I have moved the from the scripts declaration ( ScriptsToProcess) to the ModuleList in the .psd1

i.e.
ModuleList = @(PoshStack-OpenStackCompute.pm1, etc...)

This seems to make everything a bit cleaner in my opinion and help with exporting functions, variables and commands.

I was going to move some stuff around and do a pull request, but wanted to check with you first to see if there are any reasons why not to do it this way.

Regards

**Comment by DonSchenck** [comment]
Please, by all means, have at it! Thanks for catching this ... any contributions would be VERY much appreciated.

**Comment by gomker** [comment]
Wrapped up in commit bee03cf9d71a4067d0fbdcb79a00bef1b92ef92c
