### ISSUE TITLE
Update-OpenStackComputeServer requires all fields even if you only want to update one

### ISSUE THREAD

**Issue by jdobem** [DonSchenck/PoshStack#316]
If I try  to update a single property like AccessIPv4

Update-OpenStackComputeServer -Account foo -ServerId ID -AccessIPv4 "some_IP"  
 
however it tells me 
Cannot convert argument "accessIPv6", with value: "", for "UpdateServer" to type "System.Net.IPAddress" 
 
If I give him accessIPv6, then asks me for ServerName.

While it does work, if you provide all info, it's error prone.
Ideally, we should be able to input only field we want to change.

Thanks,
Jose

**Comment by DonSchenck** [comment]
PowerShell wants *all* of the parameters when calling a .NET DLL; that is, it does not allow calling .NET dll's with named parameters when accommodating optional parameters.

A possible fix -- but it will be a performance hit -- is to fetch the server, store the current values, and them merge them with the values passed into Update-OpenStackComputeServer to produce the required signature for calling the DLL.

**Comment by DonSchenck** [comment]
Hmmm ... perhaps setting the DEFAULT value to each parameter of Update-OpenStackComputeServer to [System.Management.Automation.Language.NullString]::Value will work!

I'm attempting this.

**Comment by DonSchenck** [comment]
That wasn't the answer, but I DID find the answer ... an answer that will be incorporated all across PoshStack where applicable: Accepting the parameter as a string -- in this case, AccessIPv4, and then converting it into the necessary type -- [System.Net.IPAddress] -- INSIDE the function solves the problem. Casting it to the correct type and passing the value, whether a full or empty/null string, works.
